"use client";

import dynamic from "next/dynamic";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import CursorShortcuts from "@/components/CursorShortcuts";
import Footer from "@/components/Footer";

const MonacoEditor = dynamic(() => import("@monaco-editor/react"), { ssr: false });

const examplePrompts = [
  "Create a responsive React component for a modal dialog with accessibility features",
  "Generate a TypeScript interface for a user profile with validation",
  "Write a custom hook for managing local storage state",
  "Create a Tailwind CSS animation for a loading spinner"
];

export default function BuilderTerminalPage() {
  const [prompt, setPrompt] = useState("// Cursor için bir prompt yaz...");
  const [output, setOutput] = useState(`// RunBoyRun Builder Terminal
// Prompt'unu yaz ve "Çalıştır" butonuna bas!

function welcomeToRunBoyRun() {
  console.log("🚀 Hoş geldin, builder!");
  console.log("Bu terminal senin yaratıcılığın için hazırlandı.");
  
  return "Hadi başlayalım!";
}

welcomeToRunBoyRun();`);

  const handleRun = () => {
    // Mock AI response - gerçek AI entegrasyonu sonra eklenebilir
    const mockOutput = `// Prompt: ${prompt}

// AI Generated Code:
import React, { useState } from 'react';

export default function GeneratedComponent() {
  const [isActive, setIsActive] = useState(false);
  
  return (
    <div className="p-4 rounded-lg border">
      <h2 className="text-xl font-semibold mb-4">
        Generated by RunBoyRun AI
      </h2>
      <button 
        onClick={() => setIsActive(!isActive)}
        className={\`px-4 py-2 rounded transition-colors \${
          isActive ? 'bg-blue-500 text-white' : 'bg-gray-200'
        }\`}
      >
        {isActive ? 'Active' : 'Inactive'}
      </button>
    </div>
  );
}

// Bu kod Cursor'a kopyalanmaya hazır! 🎯`;
    
    setOutput(mockOutput);
  };

  const loadExample = (example: string) => {
    setPrompt(example);
  };

  return (
    <main className="py-12">
      <div className="max-w-6xl mx-auto px-6 space-y-8">
        <header className="text-center space-y-4">
          <h1 className="text-4xl font-bold">👨‍💻 Builder Terminal</h1>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            RunBoyRun için özel bir kod oyun alanı. Prompt yaz, çıktıyı anında gör, Cursor'a kopyala!
          </p>
        </header>

        <div className="grid gap-6">
          <section>
            <h2 className="text-xl font-semibold mb-3">💡 Prompt'unu Yaz</h2>
            <Textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="Örnek: 'Bir React bileşeni yaz, butona tıklayınca renk değişsin'"
              className="min-h-[120px] font-mono"
            />
            
            <div className="flex flex-wrap gap-2 mt-3">
              <span className="text-sm text-muted-foreground">Örnekler:</span>
              {examplePrompts.map((example, index) => (
                <button
                  key={index}
                  onClick={() => loadExample(example)}
                  className="text-xs bg-muted hover:bg-muted/80 px-2 py-1 rounded transition-colors"
                >
                  {example.slice(0, 30)}...
                </button>
              ))}
            </div>
          </section>

          <Button onClick={handleRun} className="w-fit">
            🎬 Promptu Çalıştır
          </Button>

          <section>
            <h2 className="text-xl font-semibold mb-3">⚡ Generated Code</h2>
            <div className="border rounded-lg overflow-hidden bg-[#1e1e1e]">
              <MonacoEditor
                height="500px"
                defaultLanguage="javascript"
                value={output}
                theme="vs-dark"
                options={{ 
                  readOnly: false,
                  fontSize: 14,
                  minimap: { enabled: false },
                  scrollBeyondLastLine: false,
                  automaticLayout: true
                }}
              />
            </div>
            <p className="text-sm text-muted-foreground mt-2">
              💡 Bu kodu düzenleyebilir ve Cursor'a kopyalayabilirsin!
            </p>
          </section>

          <CursorShortcuts />
        </div>
      </div>
      <Footer />
    </main>
  );
} 